HeaderB header

# 0: sol_status
string  sol_status

# 1: pos_type
string  pos_type

# 2: sol_age
float32 sol_age

# 3: dr_age
float32 dr_age

# 4: roll
float64 roll

# 5: pitch
float64 pitch

# 6: heading
float64 heading

# 7: acc_x
float64 acc_x

# 8: acc_y
float64 acc_y

# 9: acc_z
float64 acc_z

# 10: gyro_x
float64 gyro_x

# 11: gyro_y
float64 gyro_y

# 12: gyro_z
float64 gyro_z

# 13~14: reserved
int32[2] reserved