# Header
string sync

# UTC 
string utc_time

# atitude
float64 latitude
string latitude_direction

# longitude
float64 longitude
string longitude_direction

# fix_quality
int32 fix_quality

# num_satellites
int32 num_satellites

# HDOP 
float64 hdop

# altitude
float64 altitude

# altitude_unit (M)
string altitude_unit

# geoid_separation
float64 geoid_separation

# geoid_separation_unit (M)
string geoid_separation_unit

# DGPS (S)
float64 dgps_age

# DGPS ID
int32 dgps_station_id

